#!/bin/bash

# Get an opt code from yubi key using rofi
setxkbmap fr bepo

# Call menu
SEL=$(ykman oath accounts list 2>/dev/null | rofi -dmenu -i -p "Select Application" -a 0 -no-custom)
SEL=$(echo "$SEL" | cut -d":" -f 1)

if [ -z "$SEL" ]; then
    exit
fi

OUT=$(ykman oath accounts code "$SEL" 2>/dev/null | awk '{print $NF}' | tr -d "\n")
# | xclip -selection clipboard &> /dev/null
# echo "Code for $SEL copied!"
printf '%s' "$OUT" | xdotool type --delay 30 --clearmodifiers --file -
